#pragma once
#ifndef DEFINE_STAGES_H
#define DEFINE_STAGES_H

// les étapes
#define STAGE_UNDEF				100
#define STAGE_TEMP				101
#define STAGE_EQ_LINE			0
#define STAGE_CONT_ADSORPTON	1
#define	STAGE_SMALL_DOSES		2
#define STAGE_MEDIUM_DOSES		3
#define STAGE_BIG_DOSES			4
#define	STAGE_DESORPTION		5
#define	STAGE_UNDER_VACUUM		6


#define STAGE_EQUILIBRATION				0
#define STAGE_ADSORPTION				1
#define	STAGE_DESORPTION				2
#define STAGE_CONTINUOUS_ADSORPTION		3
#define STAGE_VERIFICATIONS				4
#define	STAGE_END_AUTOMATIC				6

#define STEP_VERIFICATIONS_SECURITY				0
#define STEP_VERIFICATIONS_VALVES				1
#define	STEP_VERIFICATIONS_PRESSURE				2
#define STEP_VERIFICATIONS_TEMPERATURE			3
#define STEP_VERIFICATIONS_COMPLETE				4


#define STEP_STATUS_START			0
#define STEP_STATUS_INPROGRESS		1
#define	STEP_STATUS_END				2


#define SUBSTEP_STATUS_START			0
#define SUBSTEP_STATUS_INJECTION		1
#define SUBSTEP_STATUS_INJECTION_CHK	2
#define SUBSTEP_STATUS_INJECTION_ABORT	3
#define SUBSTEP_STATUS_ADSORPTION		4
#define	SUBSTEP_STATUS_END				5
#endif