//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by ParametresAppareil.rc


#define IDD_PARAMETRES_APPAREIL         107


#define IDC_EDIT_SENSIBILITE_CALO       1041
#define IDC_SPIN_SENSIBILITE_CALO       1046
#define IDC_EDIT_SENSIBILITE_CAPTEUR_BASSE_PRESSION 1060
#define IDC_SPIN_SENSIBILITE_CAPTEUR_BASSE_PRESSION 1061
#define IDC_EDIT_SENSIBILITE_CAPTEUR_HAUTE_PRESSION 1062
#define IDC_SPIN_SENSIBILITE_CAPTEUR_HAUTE_PRESSION 1063
#define IDC_EDIT_PRESSION_SECURITE_CAPTEUR_BASSE_PRESSION 1064
#define IDC_SPIN_PRESSION_SECURITE_CAPTEUR_BASSE_PRESSION 1065
#define IDC_EDIT_PRESSION_SECURITE_CAPTEUR_HAUTE_PRESSION 1066
#define IDC_SPIN_PRESSION_SECURITE_CAPTEUR_HAUTE_PRESSION 1067
#define IDC_EDIT_PRESSION_LIMITE_VIDE   1068
#define IDC_SPIN_PRESSION_LIMITE_VIDE   1069
#define IDC_EDIT_VOLUME_REF             1070
#define IDC_SPIN_VOLUME_REF             1071
#define IDC_EDIT_VOLUME_P6              1072
#define IDC_SPIN_VOLUME_P6              1073
#define IDC_NOM_CALO                    1042
#define IDC_ENTETE_FICHIER              1043
#define IDC_CHECK_ACTIVATION_SECURITE   1044
#define IDC_CHECK_TUYERE_SONIQUE        1147

// Valeurs par défaut suivantes des nouveaux objets
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        101
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1001
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
