//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Gaz.rc
//
#define IDD_AJOUT_GAZ								238
#define IDD_MODIF_GAZ								239
#define IDD_SUPPR_GAZ								340

// Ajout Gaz

#define IDC_EDIT_NOM_AJOUT_GAZ						2041
#define IDC_EDIT_SYMBOLE_AJOUT_GAZ					2042
#define IDC_EDIT_MASSE_MOLECULAIRE_AJOUT_GAZ		2044
#define IDC_SPIN_MASSE_MOLECULAIRE_AJOUT_GAZ		2048
#define IDC_EDIT_TEMPERATURE_CRITIQUE_AJOUT_GAZ		2043
#define IDC_SPIN_TEMPERATURE_CRITIQUE_AJOUT_GAZ		2049
#define IDC_EDIT_PRESSION_CRITIQUE_AJOUT_GAZ		2045
#define IDC_SPIN_PRESSION_CRITIQUE_AJOUT_GAZ		2050
#define IDC_EDIT_TEMPERATURE_EBULLITION_AJOUT_GAZ	2047
#define IDC_SPIN_TEMPERATURE_EBULLITION_AJOUT_GAZ	2051
#define IDC_EDIT_OMEGA_AJOUT_GAZ					2046
#define IDC_SPIN_OMEGA_AJOUT_GAZ					2052
#define IDC_EDIT_AJOUT_GAZ							2053
#define IDC_ADD_GAS									2040

// EXPERIMENT_TYPE_MODIFY Gaz
#define IDC_COMBO_MODIF_GAZ							2114
#define IDC_EDIT_NOM_MODIF_GAZ						2115
#define IDC_EDIT_SYMBOLE_MODIF_GAZ					2116
#define IDC_EDIT_MASSE_MOLECULAIRE_MODIF_GAZ		2117
#define IDC_SPIN_MASSE_MOLECULAIRE_MODIF_GAZ		2118
#define IDC_EDIT_TEMPERATURE_CRITIQUE_MODIF_GAZ		2119
#define IDC_SPIN_TEMPERATURE_CRITIQUE_MODIF_GAZ		2120
#define IDC_EDIT_PRESSION_CRITIQUE_MODIF_GAZ		2121
#define IDC_SPIN_PRESSION_CRITIQUE_MODIF_GAZ		2122
#define IDC_EDIT_TEMPERATURE_EBULLITION_MODIF_GAZ	2123
#define IDC_SPIN_TEMPERATURE_EBULLITION_MODIF_GAZ	2124
#define IDC_EDIT_OMEGA_MODIF_GAZ					2125
#define IDC_SPIN_OMEGA_MODIF_GAZ					2126
#define IDC_EDIT_MODIF_GAZ							2127
#define IDC_MODIFY_GAS								2105

// Suppr Gaz
#define IDC_COMBO_SUPPR_GAZ							2128
#define IDC_EDIT_SUPPR_GAZ							2129
#define IDC_DELETE_GAS								2110

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        101
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1000
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
