//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by ParametresAppareil.rc


#define IDD_PARAMETRES_APPAREIL								6607


#define IDC_EDIT_SENSIBILITE_CALO							6041
#define IDC_SPIN_SENSIBILITE_CALO							6046
#define IDC_EDIT_SENSIBILITE_CAPTEUR_BASSE_PRESSION			6060
#define IDC_SPIN_SENSIBILITE_CAPTEUR_BASSE_PRESSION			6061
#define IDC_EDIT_SENSIBILITE_CAPTEUR_HAUTE_PRESSION			6062
#define IDC_SPIN_SENSIBILITE_CAPTEUR_HAUTE_PRESSION			6063
#define IDC_EDIT_PRESSION_SECURITE_CAPTEUR_BASSE_PRESSION	6064
#define IDC_SPIN_PRESSION_SECURITE_CAPTEUR_BASSE_PRESSION	6065
#define IDC_EDIT_PRESSION_SECURITE_CAPTEUR_HAUTE_PRESSION	6066
#define IDC_SPIN_PRESSION_SECURITE_CAPTEUR_HAUTE_PRESSION	6067
#define IDC_EDIT_PRESSION_LIMITE_VIDE						6068
#define IDC_SPIN_PRESSION_LIMITE_VIDE						6069
#define IDC_EDIT_VOLUME_REF									6070
#define IDC_SPIN_VOLUME_REF									6071
#define IDC_EDIT_VOLUME_P6									6072
#define IDC_SPIN_VOLUME_P6									6073
#define IDC_NOM_CALO										6042
#define IDC_ENTETE_FICHIER									6043
#define IDC_CHECK_ACTIVATION_SECURITE						6044
#define IDC_CHECK_TUYERE_SONIQUE							6147

// Valeurs par défaut suivantes des nouveaux objets
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        101
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1001
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
