//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Gaz.rc
//
#define IDD_AJOUT_GAZ                   138
#define IDD_MODIF_GAZ                   139
#define IDD_SUPPR_GAZ                   140

// Ajout Gaz

#define IDC_EDIT_NOM_AJOUT_GAZ          1041
#define IDC_EDIT_SYMBOLE_AJOUT_GAZ      1042
#define IDC_EDIT_MASSE_MOLECULAIRE_AJOUT_GAZ 1044
#define IDC_SPIN_MASSE_MOLECULAIRE_AJOUT_GAZ 1048
#define IDC_EDIT_TEMPERATURE_CRITIQUE_AJOUT_GAZ 1043
#define IDC_SPIN_TEMPERATURE_CRITIQUE_AJOUT_GAZ 1049
#define IDC_EDIT_PRESSION_CRITIQUE_AJOUT_GAZ 1045
#define IDC_SPIN_PRESSION_CRITIQUE_AJOUT_GAZ 1050
#define IDC_EDIT_TEMPERATURE_EBULLITION_AJOUT_GAZ 1047
#define IDC_SPIN_TEMPERATURE_EBULLITION_AJOUT_GAZ 1051
#define IDC_EDIT_OMEGA_AJOUT_GAZ        1046
#define IDC_SPIN_OMEGA_AJOUT_GAZ        1052
#define IDC_EDIT_AJOUT_GAZ              1053
#define IDC_AJOUTER                     1040

// Modif Gaz
#define IDC_COMBO_MODIF_GAZ             1114
#define IDC_EDIT_NOM_MODIF_GAZ          1115
#define IDC_EDIT_SYMBOLE_MODIF_GAZ      1116
#define IDC_EDIT_MASSE_MOLECULAIRE_MODIF_GAZ 1117
#define IDC_SPIN_MASSE_MOLECULAIRE_MODIF_GAZ 1118
#define IDC_EDIT_TEMPERATURE_CRITIQUE_MODIF_GAZ 1119
#define IDC_SPIN_TEMPERATURE_CRITIQUE_MODIF_GAZ 1120
#define IDC_EDIT_PRESSION_CRITIQUE_MODIF_GAZ 1121
#define IDC_SPIN_PRESSION_CRITIQUE_MODIF_GAZ 1122
#define IDC_EDIT_TEMPERATURE_EBULLITION_MODIF_GAZ 1123
#define IDC_SPIN_TEMPERATURE_EBULLITION_MODIF_GAZ 1124
#define IDC_EDIT_OMEGA_MODIF_GAZ        1125
#define IDC_SPIN_OMEGA_MODIF_GAZ        1126
#define IDC_EDIT_MODIF_GAZ              1127
#define IDC_MODIFIER                    1105

// Suppr Gaz
#define IDC_COMBO_SUPPR_GAZ             1128
#define IDC_EDIT_SUPPR_GAZ              1129
#define IDC_SUPPRIMER                   1110


// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        101
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1000
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
