//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by OngletsEtapes.rc
//
#define IDD_ADSORPTION_CONTINUE         131
#define IDD_PETITES_DOSES               104
#define IDD_MOYENNES_DOSES               207
#define IDD_GRANDES_DOSES               106
#define IDD_DESORPTION                  105


// Adsorption Continue
#define IDC_CHECK_ADSORPTION_CONTINUE   1044
#define IDC_EDIT_TEMPS_ETALONNAGE_DEBIT 1041
#define IDC_SPIN_TEMPS_ETALONNAGE_DEBIT 1046
#define IDC_EDIT_TEMPS_ETALONNAGE_VOLUME_INTER 1042
#define IDC_SPIN_TEMPS_ETALONNAGE_VOLUME_INTER 1047
#define IDC_EDIT_TEMPS_EQUILIBRE_CONTINUE 1043
#define IDC_SPIN_TEMPS_EQUILIBRE_CONTINUE 1048
#define IDC_EDIT_TEMPS_FINAL_EQUILIBRE  1060
#define IDC_SPIN_TEMPS_FINAL_EQUILIBRE  1061
#define IDC_EDIT_PRESSION_FINALE_ADSORPTION_CONTINUE 1045
#define IDC_SPIN_PRESSION_FINALE_ADSORPTION_CONTINUE 1049

#define IDC_STATIC_AD_TED_TEXT          1065
#define IDC_STATIC_AD_TED_MIN           1066
#define IDC_STATIC_AD_TEVI_TEXT         1069
#define IDC_STATIC_AD_TEVI_MIN          1070
#define IDC_STATIC_AD_TEC_TEXT          1081
#define IDC_STATIC_AD_TEC_MIN           1103
#define IDC_STATIC_AD_TFE_TEXT          1083
#define IDC_STATIC_AD_TFE_MIN           1104
#define IDC_STATIC_AD_PF_TEXT           1082
#define IDC_STATIC_AD_PF_BAR            1085


// Petites Doses
#define IDC_CHECK_PETITES_DOSES         1064
#define IDC_EDIT_DELTA_PRESSION_PETITES_DOSES 1067
#define IDC_SPIN_DELTA_PRESSION_PETITES_DOSES 1068
#define IDC_EDIT_TEMPS_VOLUME_PETITES_DOSES 1071
#define IDC_SPIN_TEMPS_VOLUME_PETITES_DOSES 1072
#define IDC_EDIT_TEMPS_ADSORPTION_PETITES_DOSES 1083
#define IDC_SPIN_TEMPS_ADSORPTION_PETITES_DOSES 1084
#define IDC_EDIT_PRESSION_FINALE_PETITES_DOSES 1087
#define IDC_SPIN_PRESSION_FINALE_PETITES_DOSES 1088

#define IDC_STATIC_PD_DPPPD_TEXT        1065
#define IDC_STATIC_PD_DPPPD_BAR         1066
#define IDC_STATIC_PD_TEVR_TEXT         1069
#define IDC_STATIC_PD_TEVR_MIN          1070
#define IDC_STATIC_PD_TEA_TEXT          1081
#define IDC_STATIC_PD_TEA_MIN           1082
#define IDC_STATIC_PD_PF_TEXT           1085
#define IDC_STATIC_PD_PF_BAR            1086


// Moyennes Doses
#define IDC_CHECK_MOYENNES_DOSES         1189
#define IDC_EDIT_DELTA_PRESSION_MOYENNES_DOSES 1190
#define IDC_SPIN_DELTA_PRESSION_MOYENNES_DOSES 1191
#define IDC_EDIT_TEMPS_VOLUME_MOYENNES_DOSES 1192
#define IDC_SPIN_TEMPS_VOLUME_MOYENNES_DOSES 1193
#define IDC_EDIT_TEMPS_ADSORPTION_MOYENNES_DOSES 1194
#define IDC_SPIN_TEMPS_ADSORPTION_MOYENNES_DOSES 1195
#define IDC_EDIT_PRESSION_FINALE_MOYENNES_DOSES 1196
#define IDC_SPIN_PRESSION_FINALE_MOYENNES_DOSES 1197

#define IDC_STATIC_MY_DPPMY_TEXT        1165
#define IDC_STATIC_MY_DPPMY_BAR         1166
#define IDC_STATIC_MY_TEVR_TEXT         1169
#define IDC_STATIC_MY_TEVR_MIN          1170
#define IDC_STATIC_MY_TEA_TEXT          1181
#define IDC_STATIC_MY_TEA_MIN           1182
#define IDC_STATIC_MY_PF_TEXT           1185
#define IDC_STATIC_MY_PF_BAR            1186

// Grandes Doses
#define IDC_CHECK_GRANDES_DOSES         1089
#define IDC_EDIT_DELTA_PRESSION_GRANDES_DOSES 1090
#define IDC_SPIN_DELTA_PRESSION_GRANDES_DOSES 1091
#define IDC_EDIT_TEMPS_VOLUME_GRANDES_DOSES 1092
#define IDC_SPIN_TEMPS_VOLUME_GRANDES_DOSES 1093
#define IDC_EDIT_TEMPS_ADSORPTION_GRANDES_DOSES 1094
#define IDC_SPIN_TEMPS_ADSORPTION_GRANDES_DOSES 1095
#define IDC_EDIT_PRESSION_FINALE_GRANDES_DOSES 1096
#define IDC_SPIN_PRESSION_FINALE_GRANDES_DOSES 1097

#define IDC_STATIC_GD_DPPGD_TEXT        1065
#define IDC_STATIC_GD_DPPGD_BAR         1066
#define IDC_STATIC_GD_TEVR_TEXT         1069
#define IDC_STATIC_GD_TEVR_MIN          1070
#define IDC_STATIC_GD_TEA_TEXT          1081
#define IDC_STATIC_GD_TEA_MIN           1082
#define IDC_STATIC_GD_PF_TEXT           1085
#define IDC_STATIC_GD_PF_BAR            1086

// Désorption
#define IDC_CHECK_DESORPTION            1044
#define IDC_EDIT_DELTA_PRESSION_DESORPTION 1098
#define IDC_SPIN_DELTA_PRESSION_DESORPTION 1099
#define IDC_EDIT_TEMPS_VOLUME_DESORPTION 1042
#define IDC_SPIN_TEMPS_VOLUME_DESORPTION 1047
#define IDC_EDIT_TEMPS_DESORPTION       1043
#define IDC_SPIN_TEMPS_DESORPTION       1048
#define IDC_EDIT_PRESSION_FINALE_DESORPTION 1045
#define IDC_SPIN_PRESSION_FINALE_DESORPTION 1049
#define IDC_CHECK_DESORPTION_DERNIERE_ETAPE 1147

#define IDC_STATIC_D_DPD_TEXT           1065
#define IDC_STATIC_D_DPD_BAR            1066
#define IDC_STATIC_D_TEVR_TEXT          1069
#define IDC_STATIC_D_TEVR_MIN           1070
#define IDC_STATIC_D_TED_TEXT           1081
#define IDC_STATIC_D_TED_MIN            1086
#define IDC_STATIC_D_PF_TEXT            1082
#define IDC_STATIC_D_PF_BAR             1085


// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        101
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1000
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
