//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Cellule.rc
//
#define IDD_AJOUT_CELLULE               141
#define IDD_MODIF_CELLULE               142
#define IDD_SUPPR_CELLULE               143

// Ajout Cellule
#define IDC_EDIT_AJOUT_NUMERO_CELLULE   1041
#define IDC_EDIT_AJOUT_VOLUME_CELLULE   1042
#define IDC_SPIN_AJOUT_VOLUME_CELLULE   1047
#define IDC_EDIT_AJOUT_VOLUME_CALO      1043
#define IDC_SPIN_AJOUT_VOLUME_CALO      1048
#define IDC_EDIT_MESSAGE_AJOUT_CELLULE  1045
#define IDC_AJOUTER                     1040

// MODIFY_WINDOW Cellule
#define IDC_COMBO_MODIF_CELLULE         1131
#define IDC_EDIT_MODIF_NUMERO_CELLULE   1041
#define IDC_SPIN_MODIF_NUMERO_CELLULE   1046
#define IDC_EDIT_MODIF_VOLUME_CELLULE   1132
#define IDC_SPIN_MODIF_VOLUME_CELLULE   1133
#define IDC_EDIT_MODIF_VOLUME_CALO      1134
#define IDC_SPIN_MODIF_VOLUME_CALO      1135
#define IDC_EDIT_MESSAGE_MODIF_CELLULE  1136
#define IDC_MODIFIER                    1105

// Suppr cellule
#define IDC_COMBO_SUPPR_NUMERO_CELLULE  1137
#define IDC_EDIT_SUPPR_VOLUME_CELLULE   1138
#define IDC_EDIT_SUPPR_VOLUME_CALO      1139
#define IDC_EDIT_MESSAGE_SUPPR_CELLULE  1140
#define IDC_SUPPRIMER                   1110


// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        101
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1000
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
