//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by ConnectionPort.rc
//
#define IDD_CONNECTION_PORT             130
#define IDC_COMBO_INSTRUMENT1_KEITHLEY_VOIE2 1001
#define IDC_COMBO_INSTRUMENT2_KEITHLEY_VOIE2 1002
#define IDC_COMBO_INSTRUMENT1_KEITHLEY_VOIE3 1003
#define IDC_COMBO_INSTRUMENT3_KEITHLEY_VOIE2 1003
#define IDC_CHECK_INSTRUMENT1_KEITHLEY_VOIE1 1044
#define IDC_CHECK_INSTRUMENT2_KEITHLEY_VOIE1 1045
#define IDC_CHECK_INSTRUMENT3_KEITHLEY_VOIE1 1046
#define IDC_PORT_INSTRUMENT2            1048
#define IDC_PORT_VANNES                 1049
#define IDC_PORT_TEMPERATURES           1050
#define IDC_PORT_INSTRUMENT1            1051
#define IDC_PORT_INSTRUMENT3            1052
#define IDC_CHECK_INSTRUMENT1_KEITHLEY_VOIE2 1147
#define IDC_COMBO_TYPE_INSTRUMENT1      1148
#define IDC_COMBO_TYPE_INSTRUMENT2      1149
#define IDC_COMBO_TYPE_INSTRUMENT3      1150
#define IDC_CHECK_INSTRUMENT2_KEITHLEY_VOIE2 1151
#define IDC_CHECK_INSTRUMENT3_KEITHLEY_VOIE2 1152
#define IDC_COMBO_INSTRUMENT1_MENSOR    1153
#define IDC_COMBO_INSTRUMENT2_MENSOR    1156
#define IDC_COMBO_INSTRUMENT3_MENSOR    1157

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        101
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1002
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
