//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by DialogCell.rc
//
#define IDD_TABDIVERS							3304
#define IDD_TABDOSES							3305
#define IDD_TABGENERAL							3303
#define IDD_AJOUT_CELLULE						3341
#define IDD_MODIF_CELLULE						3342
#define IDD_SUPPR_CELLULE						3343
#define IDC_ADD_CELL							3040
#define IDC_EDIT_AJOUT_NUMERO_CELLULE			3041
#define IDC_EDIT_MODIF_NUMERO_CELLULE			3041
#define IDC_EDIT_AJOUT_VOLUME_CELLULE			3042
#define IDC_EDIT_AJOUT_VOLUME_CALO				3043
#define IDC_EDIT_MESSAGE_AJOUT_CELLULE			3045
#define IDC_SPIN_MODIF_NUMERO_CELLULE			3046
#define IDC_SPIN_AJOUT_VOLUME_CELLULE			3047
#define IDC_SPIN_AJOUT_VOLUME_CALO				3048
#define IDC_MODIFY_CELL							3105
#define IDC_DELETE_CELL							3110
#define IDC_COMBO_MODIF_CELLULE					3131
#define IDC_EDIT_MODIF_VOLUME_CELLULE			3132
#define IDC_SPIN_MODIF_VOLUME_CELLULE			3133
#define IDC_EDIT_MODIF_VOLUME_CALO				3134
#define IDC_SPIN_MODIF_VOLUME_CALO				3135
#define IDC_EDIT_MESSAGE_MODIF_CELLULE			3136
#define IDC_COMBO_SUPPR_NUMERO_CELLULE			3137
#define IDC_EDIT_SUPPR_VOLUME_CELLULE			3138
#define IDC_EDIT_SUPPR_VOLUME_CALO				3139
#define IDC_EDIT_MESSAGE_SUPPR_CELLULE			3140

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        101
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1000
#define _APS_NEXT_SYMED_VALUE           106
#endif
#endif
