//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by ParametresAppareil.rc
//
#define IDC_SPIN_SENSIBILITE_CAPTEUR_BASSE_PRESSION 6061
#define IDC_SPIN_SENSIBILITE_CAPTEUR_HAUTE_PRESSION 6063
#define IDC_SPIN_PRESSION_SECURITE_CAPTEUR_BASSE_PRESSION 6065
#define IDC_SPIN_PRESSION_SECURITE_CAPTEUR_HAUTE_PRESSION 6067
#define IDC_SPIN_PRESSION_SECURITE_CAPTEUR_HAUTE_PRESSION2 6068
#define IDC_SPIN_PRESSION_LIMITE_VIDE   6069
#define IDC_SPIN_PRESSION_SECURITE_CAPTEUR_HAUTE_PRESSION3 6070
#define IDC_SPIN_VOLUME_REF             6071
#define IDC_SPIN_PRESSION_SECURITE_CAPTEUR_HAUTE_PRESSION4 6072
#define IDC_SPIN_VOLUME_P6              6073
#define IDC_SPIN_PRESSION_SECURITE_CAPTEUR_HAUTE_PRESSION5 6074
#define IDC_SPIN_PRESSION_SECURITE_CAPTEUR_HAUTE_PRESSION6 6075
#define IDC_SPIN_PRESSION_SECURITE_CAPTEUR_HAUTE_PRESSION7 6076
#define IDC_SPIN_PRESSION_SECURITE_CAPTEUR_HAUTE_PRESSION8 6077
#define IDC_SPIN_PRESSION_SECURITE_CAPTEUR_HAUTE_PRESSION9 6078
#define IDC_SPIN_PRESSION_SECURITE_CAPTEUR_HAUTE_PRESSION10 6079
#define IDC_SPIN_PRESSION_SECURITE_CAPTEUR_HAUTE_PRESSION11 6080
#define IDC_SPIN_PRESSION_SECURITE_CAPTEUR_HAUTE_PRESSION12 6081
#define IDC_SPIN_PRESSION_SECURITE_CAPTEUR_HAUTE_PRESSION13 6082
#define IDC_EDIT_SENSIBILITE_CALO       6301
#define IDC_EDIT_SENSIBILITE_CAPTEUR_BASSE_PRESSION 6302
#define IDC_EDIT_SENSIBILITE_CAPTEUR_HAUTE_PRESSION 6303
#define IDC_EDIT_PRESSION_SECURITE_CAPTEUR_BASSE_PRESSION 6304
#define IDC_EDIT_PRESSION_SECURITE_CAPTEUR_HAUTE_PRESSION 6305
#define IDC_EDIT_PRESSION_LIMITE_VIDE   6306
#define IDC_EDIT_VOLUME_REF             6307
#define IDC_EDIT_VOLUME_P6              6308
#define IDC_NOM_CALO                    6309
#define IDC_ENTETE_FICHIER              6310
#define IDC_SPIN_SENSIBILITE_CALO       6313
#define IDC_EDIT_PRESSION_SECURITE_CAPTEUR_HAUTE_PRESSION2 6313
#define IDC_EDIT_PRESSION_SECURITE_CAPTEUR_HAUTE_PRESSION3 6314
#define IDC_EDIT_PRESSION_SECURITE_CAPTEUR_HAUTE_PRESSION4 6315
#define IDC_EDIT_PRESSION_SECURITE_CAPTEUR_HAUTE_PRESSION5 6316
#define IDC_EDIT_PRESSION_SECURITE_CAPTEUR_HAUTE_PRESSION6 6317
#define IDC_EDIT_PRESSION_SECURITE_CAPTEUR_HAUTE_PRESSION7 6318
#define IDC_EDIT_PRESSION_SECURITE_CAPTEUR_HAUTE_PRESSION8 6319
#define IDC_EDIT_PRESSION_SECURITE_CAPTEUR_HAUTE_PRESSION9 6320
#define IDC_EDIT_PRESSION_SECURITE_CAPTEUR_HAUTE_PRESSION10 6321
#define IDC_EDIT_PRESSION_SECURITE_CAPTEUR_HAUTE_PRESSION11 6322
#define IDC_EDIT_PRESSION_SECURITE_CAPTEUR_HAUTE_PRESSION12 6323
#define IDC_EDIT_PRESSION_SECURITE_CAPTEUR_HAUTE_PRESSION13 6324
#define IDD_PARAMETRES_APPAREIL         6607
#define IDC_CHECK_ACTIVATION_SECURITE   6344
#define IDC_CHECK_TUYERE_SONIQUE        6345

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        101
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1001
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
