//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by OngletsEtapes.rc
//
#define IDD_ADSORPTION_CONTINUE         5001
#define IDD_DESORPTION                  5005
#define IDD_DOSES                       5006
#define IDC_EDIT_TEMPS_ETALONNAGE_DEBIT 5041
#define IDC_EDIT_TEMPS_ETALONNAGE_VOLUME_INTER 5042
#define IDC_EDIT_TEMPS_EQUILIBRE_CONTINUE 5043
#define IDC_CHECK_ADSORPTION_CONTINUE   5044
#define IDC_EDIT_PRESSION_FINALE_ADSORPTION_CONTINUE 5045
#define IDC_SPIN_TEMPS_ETALONNAGE_DEBIT 5046
#define IDC_SPIN_TEMPS_ETALONNAGE_VOLUME_INTER 5047
#define IDC_SPIN_TEMPS_EQUILIBRE_CONTINUE 5048
#define IDC_SPIN_PRESSION_FINALE_ADSORPTION_CONTINUE 5049
#define IDC_EDIT_TEMPS_FINAL_EQUILIBRE  5060
#define IDC_SPIN_TEMPS_FINAL_EQUILIBRE  5061
#define IDC_STATIC_AD_TED_TEXT          5065
#define IDC_STATIC_AD_TED_MIN           5066
#define IDC_STATIC_AD_TEVI_TEXT         5069
#define IDC_STATIC_AD_TEVI_MIN          5070
#define IDC_STATIC_AD_TEC_TEXT          5081
#define IDC_STATIC_AD_PF_TEXT           5082
#define IDC_STATIC_AD_PF_BAR            5085
#define IDC_STATIC_AD_TEC_MIN           5086
#define IDC_STATIC_AD_TFE_TEXT          5087
#define IDC_STATIC_AD_TFE_MIN           5088
#define IDC_EDIT_TEMPS_VOLUME_DESORPTION 5442
#define IDC_EDIT_TEMPS_DESORPTION       5443
#define IDC_CHECK_DESORPTION            5444
#define IDC_EDIT_PRESSION_FINALE_DESORPTION 5445
#define IDC_CHECK_DESORPTION_DERNIERE_ETAPE 5447
#define IDC_SPIN_TEMPS_DESORPTION       5448
#define IDC_SPIN_PRESSION_FINALE_DESORPTION 5449
#define IDC_STATIC_D_DPD_TEXT           5465
#define IDC_STATIC_D_DPD_BAR            5466
#define IDC_STATIC_D_TEVR_TEXT          5469
#define IDC_STATIC_D_TEVR_MIN           5470
#define IDC_STATIC_D_TED_TEXT           5481
#define IDC_STATIC_D_PF_TEXT            5482
#define IDC_STATIC_D_PF_BAR             5485
#define IDC_STATIC_D_TED_MIN            5486
#define IDC_SPIN_TEMPS_VOLUME_DESORPTION 5488
#define IDC_EDIT_DELTA_PRESSION_DESORPTION 5498
#define IDC_SPIN_DELTA_PRESSION_DESORPTION 5499
#define IDC_STATIC_DPPMY_TEXT           5565
#define IDC_STATIC_DPPMY_BAR            5566
#define IDC_STATIC_TEVR_TEXT            5569
#define IDC_STATIC_TEVR_MIN             5570
#define IDC_STATIC_TEA_TEXT             5581
#define IDC_STATIC_TEA_MIN              5582
#define IDC_STATIC_PF_TEXT              5585
#define IDC_STATIC_PF_BAR               5586
#define IDC_CHECK_DOSES                 5589
#define IDC_EDIT_DELTA_PRESSION_DOSES   5590
#define IDC_SPIN_DELTA_PRESSION_DOSES   5591
#define IDC_EDIT_TEMPS_VOLUME_DOSES     5592
#define IDC_SPIN_TEMPS_VOLUME_DOSES     5593
#define IDC_EDIT_TEMPS_ADSORPTION_DOSES 5594
#define IDC_SPIN_TEMPS_ADSORPTION_DOSES 5595
#define IDC_EDIT_PRESSION_FINALE_DOSES  5596
#define IDC_SPIN_PRESSION_FINALE_DOSES  5597
#define IDC_BUTTON_ADS_REMOVE           5598
#define IDC_BUTTON_DES_REMOVE           5599

#define IDD_GENERAL                     5601
#define IDD_DIVERS                      5602
#define IDC_SPIN_MASSE_ECHANTILLON      5603
#define IDC_NOM_FICHIER                 5604
#define IDC_NOM_ECHANTILLON             5605
#define IDC_MASSE_ECHANTILLON           5606
#define IDC_COMBO_EXPERIMENTATEUR       5607
#define IDC_BUTTON_EXPERIMENTATEUR      5608
#define IDC_BUTTON_GAZ                  5609
#define IDC_COMBO_GAZ                   5610
#define IDC_COMMENTAIRES                5611
#define IDC_NOM_CHEMIN                  5612
#define IDC_PARCOURIR_DOSSIER           5613
#define IDC_TEMPERATURE_EXPERIENCE      5614
#define IDC_SPIN_TEMPERATURE_EXPERIENCE 5615
#define IDC_COMBO_CELLULE               5616
#define IDC_BUTTON_CELLULE              5617
#define IDC_EDIT_VOLUME_TOTAL           5618
#define IDC_EDIT_VOLUME_CALO            5619
#define IDC_EDIT_TEMPS_LIGNE_BASE       5620
#define IDC_CHECK_MISE_SOUS_VIDE        5621
#define IDC_SPIN_TEMPS_LIGNE_BASE       5622
#define IDC_EDIT_TEMPS_VIDE             5623
#define IDC_SPIN_TEMPS_VIDE             5624
#define IDC_STATIC_MISE_SOUS_VIDE       5625
#define IDC_STATIC_MISE_SOUS_VIDE2      5626
#define IDC_PLUSADS                     5627
#define IDC_PLUSDES                     5628
#define IDC_MINUSADS                    5629
#define IDC_MINUDES                     5630


// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        103
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1001
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
