//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by ConnectionPort.rc
//
#define IDD_CONNECTION_PORT						8830
#define IDC_COMBO_INSTRUMENT1_KEITHLEY_VOIE2	8001
#define IDC_COMBO_INSTRUMENT2_KEITHLEY_VOIE2	8002
#define IDC_COMBO_INSTRUMENT3_KEITHLEY_VOIE2	8003
#define IDC_CHECK_INSTRUMENT1_KEITHLEY_VOIE1	8044
#define IDC_CHECK_INSTRUMENT2_KEITHLEY_VOIE1	8045
#define IDC_CHECK_INSTRUMENT3_KEITHLEY_VOIE1	8046
#define IDC_PORT_INSTRUMENT2					8048
#define IDC_PORT_VANNES							8049
#define IDC_PORT_TEMPERATURES					8050
#define IDC_PORT_INSTRUMENT1					8051
#define IDC_PORT_INSTRUMENT3					8052
#define IDC_COMBO_TYPE_INSTRUMENT1				8148
#define IDC_COMBO_TYPE_INSTRUMENT2				8149
#define IDC_COMBO_TYPE_INSTRUMENT3				8150
#define IDC_CHECK_INSTRUMENT1_KEITHLEY_VOIE2	8147
#define IDC_CHECK_INSTRUMENT2_KEITHLEY_VOIE2	8151
#define IDC_CHECK_INSTRUMENT3_KEITHLEY_VOIE2	8152
#define IDC_COMBO_INSTRUMENT1_MENSOR			8153
#define IDC_COMBO_INSTRUMENT2_MENSOR			8156
#define IDC_COMBO_INSTRUMENT3_MENSOR			8157

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        101
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1002
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
