//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by OngletsEtapes.rc
//
#define IDD_ADSORPTION_CONTINUE							5001
#define IDD_PETITES_DOSES								5002
#define IDD_MOYENNES_DOSES								5003
#define IDD_GRANDES_DOSES								5004
#define IDD_DESORPTION									5005
#define IDD_DOSES										5006


// Adsorption Continue
#define IDC_CHECK_ADSORPTION_CONTINUE					5044
#define IDC_EDIT_TEMPS_ETALONNAGE_DEBIT					5041
#define IDC_SPIN_TEMPS_ETALONNAGE_DEBIT					5046
#define IDC_EDIT_TEMPS_ETALONNAGE_VOLUME_INTER			5042
#define IDC_SPIN_TEMPS_ETALONNAGE_VOLUME_INTER			5047
#define IDC_EDIT_TEMPS_EQUILIBRE_CONTINUE				5043
#define IDC_SPIN_TEMPS_EQUILIBRE_CONTINUE				5048
#define IDC_EDIT_TEMPS_FINAL_EQUILIBRE					5060
#define IDC_SPIN_TEMPS_FINAL_EQUILIBRE					5061
#define IDC_EDIT_PRESSION_FINALE_ADSORPTION_CONTINUE	5045
#define IDC_SPIN_PRESSION_FINALE_ADSORPTION_CONTINUE	5049

#define IDC_STATIC_AD_TED_TEXT							5065
#define IDC_STATIC_AD_TED_MIN							5066
#define IDC_STATIC_AD_TEVI_TEXT							5069
#define IDC_STATIC_AD_TEVI_MIN							5070
#define IDC_STATIC_AD_TEC_TEXT							5081
#define IDC_STATIC_AD_PF_TEXT							5082
#define IDC_STATIC_AD_PF_BAR							5085
#define IDC_STATIC_AD_TEC_MIN							5086
#define IDC_STATIC_AD_TFE_TEXT							5087
#define IDC_STATIC_AD_TFE_MIN							5088

// Petites Doses
#define IDC_CHECK_PETITES_DOSES							5164
#define IDC_EDIT_DELTA_PRESSION_PETITES_DOSES			5167
#define IDC_SPIN_DELTA_PRESSION_PETITES_DOSES			5168
#define IDC_EDIT_TEMPS_VOLUME_PETITES_DOSES				5171
#define IDC_SPIN_TEMPS_VOLUME_PETITES_DOSES				5172
#define IDC_EDIT_TEMPS_ADSORPTION_PETITES_DOSES			5183
#define IDC_SPIN_TEMPS_ADSORPTION_PETITES_DOSES			5184
#define IDC_EDIT_PRESSION_FINALE_PETITES_DOSES			5187
#define IDC_SPIN_PRESSION_FINALE_PETITES_DOSES			5188

#define IDC_STATIC_PD_DPPPD_TEXT						5165
#define IDC_STATIC_PD_DPPPD_BAR							5166
#define IDC_STATIC_PD_TEVR_TEXT							5169
#define IDC_STATIC_PD_TEVR_MIN							5170
#define IDC_STATIC_PD_TEA_TEXT							5181
#define IDC_STATIC_PD_TEA_MIN							5182
#define IDC_STATIC_PD_PF_TEXT							5185
#define IDC_STATIC_PD_PF_BAR							5186


// Moyennes Doses
#define IDC_CHECK_MOYENNES_DOSES						5289
#define IDC_EDIT_DELTA_PRESSION_MOYENNES_DOSES			5290
#define IDC_SPIN_DELTA_PRESSION_MOYENNES_DOSES			5291
#define IDC_EDIT_TEMPS_VOLUME_MOYENNES_DOSES			5292
#define IDC_SPIN_TEMPS_VOLUME_MOYENNES_DOSES			5293
#define IDC_EDIT_TEMPS_ADSORPTION_MOYENNES_DOSES		5294
#define IDC_SPIN_TEMPS_ADSORPTION_MOYENNES_DOSES		5295
#define IDC_EDIT_PRESSION_FINALE_MOYENNES_DOSES			5296
#define IDC_SPIN_PRESSION_FINALE_MOYENNES_DOSES			5297

#define IDC_STATIC_MY_DPPMY_TEXT						5265
#define IDC_STATIC_MY_DPPMY_BAR							5266
#define IDC_STATIC_MY_TEVR_TEXT							5269
#define IDC_STATIC_MY_TEVR_MIN							5270
#define IDC_STATIC_MY_TEA_TEXT							5281
#define IDC_STATIC_MY_TEA_MIN							5282
#define IDC_STATIC_MY_PF_TEXT							5285
#define IDC_STATIC_MY_PF_BAR							5286

// Grandes Doses
#define IDC_CHECK_GRANDES_DOSES							5389
#define IDC_EDIT_DELTA_PRESSION_GRANDES_DOSES			5390
#define IDC_SPIN_DELTA_PRESSION_GRANDES_DOSES			5391
#define IDC_EDIT_TEMPS_VOLUME_GRANDES_DOSES				5392
#define IDC_SPIN_TEMPS_VOLUME_GRANDES_DOSES				5393
#define IDC_EDIT_TEMPS_ADSORPTION_GRANDES_DOSES			5394
#define IDC_SPIN_TEMPS_ADSORPTION_GRANDES_DOSES			5395
#define IDC_EDIT_PRESSION_FINALE_GRANDES_DOSES			5396
#define IDC_SPIN_PRESSION_FINALE_GRANDES_DOSES			5397

#define IDC_STATIC_GD_DPPGD_TEXT						5365
#define IDC_STATIC_GD_DPPGD_BAR							5366
#define IDC_STATIC_GD_TEVR_TEXT							5369
#define IDC_STATIC_GD_TEVR_MIN							5370
#define IDC_STATIC_GD_TEA_TEXT							5381
#define IDC_STATIC_GD_TEA_MIN							5382
#define IDC_STATIC_GD_PF_TEXT							5385
#define IDC_STATIC_GD_PF_BAR							5386

// Désorption
#define IDC_CHECK_DESORPTION							5444
#define IDC_EDIT_DELTA_PRESSION_DESORPTION				5498
#define IDC_SPIN_DELTA_PRESSION_DESORPTION				5499
#define IDC_EDIT_TEMPS_VOLUME_DESORPTION				5442
#define IDC_SPIN_TEMPS_VOLUME_DESORPTION				5488
#define IDC_EDIT_TEMPS_DESORPTION						5443
#define IDC_SPIN_TEMPS_DESORPTION						5448
#define IDC_EDIT_PRESSION_FINALE_DESORPTION				5445
#define IDC_SPIN_PRESSION_FINALE_DESORPTION				5449
#define IDC_CHECK_DESORPTION_DERNIERE_ETAPE				5447

#define IDC_STATIC_D_DPD_TEXT							5465
#define IDC_STATIC_D_DPD_BAR							5466
#define IDC_STATIC_D_TEVR_TEXT							5469
#define IDC_STATIC_D_TEVR_MIN							5470
#define IDC_STATIC_D_TED_TEXT							5481
#define IDC_STATIC_D_TED_MIN							5486
#define IDC_STATIC_D_PF_TEXT							5482
#define IDC_STATIC_D_PF_BAR								5485


// Doses
#define IDC_CHECK_DOSES									5589
#define IDC_EDIT_DELTA_PRESSION_DOSES					5590
#define IDC_SPIN_DELTA_PRESSION_DOSES					5591
#define IDC_EDIT_TEMPS_VOLUME_DOSES						5592
#define IDC_SPIN_TEMPS_VOLUME_DOSES						5593
#define IDC_EDIT_TEMPS_ADSORPTION_DOSES					5594
#define IDC_SPIN_TEMPS_ADSORPTION_DOSES					5595
#define IDC_EDIT_PRESSION_FINALE_DOSES					5596
#define IDC_SPIN_PRESSION_FINALE_DOSES					5597

#define IDC_STATIC_DPPMY_TEXT							5565
#define IDC_STATIC_DPPMY_BAR							5566
#define IDC_STATIC_TEVR_TEXT							5569
#define IDC_STATIC_TEVR_MIN								5570
#define IDC_STATIC_TEA_TEXT								5581
#define IDC_STATIC_TEA_MIN								5582
#define IDC_STATIC_PF_TEXT								5585
#define IDC_STATIC_PF_BAR								5586


// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        101
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1000
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
